
<?php $posts = $this->getPostCollection(); ?>
<?php if ($posts && $posts->count() > 0) : ?>
    <div class="box-collateral box-posts box-up-sell">
        <?php foreach ($posts as $_post) : ?>
            <div class="item">
                <a href="<?php echo $_post->getPostUrl() ?>">
                    <?php echo $_post->getTitle(); ?>
                </a><br />
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
