<?php $_posts = $this->getCollection(); ?>
<?php if ($_posts->getSize() > 0) : ?>
    <?php foreach ($_posts as $_post): ?>
        <div class="post-view">
            <div class="post-header">
                <h1 class="post-title"><a href="<?php echo Mage::getUrl($_post->getUrlKey()); ?>"><?php echo $_post->getTitle(); ?></a></h1>
                <p class="post-meta">
                    <time class="post-date"><i class="fa fa-clock-o" aria-hidden="true"></i><?php echo date('d F, Y', strtotime($_post->getPublishDate())); ?></time>
                    <span class="post-comment-link"><i class="fa fa-comment-o" aria-hidden="true"></i><a href="<?php echo Mage::getUrl($_post->getUrlKey()); ?>/#form-add">Leave a comment</a></span>
                </p>
            </div>
            <div class="post-small_image">
                <?php if ($_post->getSmallImage()) : ?>
                    <center><img src="<?php echo Mage::helper('dls_dlsblog/post_image')->init($_post, 'small_image'); ?>" alt="<?php echo $this->escapeHtml($_post->getTitile()); ?>" /></center>
                <?php endif; ?>
            </div>
            <div class="post-short_content">
                <p class="short_content"><?php echo $_post->getShortContent(); ?></p>
            </div>
            <div class="post-read-more">
                <a href="<?php echo Mage::getUrl($_post->getUrlKey()); ?>" class="read-more">[Read more...]</a>
            </div>
        </div>
    <?php endforeach; ?>
<?php endif ?>
<div class="post-paging"><?php echo $this->getPagerHtml(); ?></div>
