<?php

?>
<div class="content-header">
    <h3 class="icon-head head-categories">
        <?php echo $this->escapeHtml($this->getHeader()) . ($this->getLayoutdesignId() ? ' (' . Mage::helper('dls_dlsblog')->__('ID: %s', $this->getLayoutdesignId()) . ')' : '') ?>
    </h3>
    <p class="content-buttons form-buttons">
        <?php echo $this->getResetButtonHtml() ?>
        <?php if ($this->getLayoutdesignId()): ?>
            <?php echo $this->getDeleteButtonHtml() ?>
        <?php endif; ?>
        <?php echo $this->getAdditionalButtonsHtml(); ?>
        <?php echo $this->getSaveButtonHtml() ?>
    </p>
</div>
<?php echo $this->getTabsHtml() ?>
<iframe name="iframeSave" style="display:none; width:100%;" src="<?php echo $this->getJsUrl() ?>blank.html"></iframe>
<form target="iframeSave" id="layoutdesign_edit_form" action="<?php echo $this->getSaveUrl() ?>" method="post" enctype="multipart/form-data">
    <div class="no-display">
        <input type="hidden" name="isIframe" value="1" />
        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
        <input type="hidden" name="active_tab_id" id="active_tab_id" value="" />
    </div>
    <div id="layoutdesign_tab_content"></div>
</form>
<script type="text/javascript">
//<![CDATA[
    layoutdesignForm = new varienForm('layoutdesign_edit_form');
    layoutdesignForm.submit= function (url) {
        this.errorSections = $H({});
        this.canShowError = true;
        this.submitUrl = url;
        if (this.validator && this.validator.validate()) {
            if (this.validationUrl) {
                this._validate();
            } else {
                if (this.isSubmitted) {
                    return false;
                }
                this.isSubmitted = true;
                this._submit();
            }
            displayLoadingMask();
            return true;
        }
        return false;
    };
    layoutdesignForm.refreshPath = function () {
        layoutdesignId = this.getLayoutdesignId();
        if (!layoutdesignId) {
            return false;
        }
        var refreshPathSuccess = function(transport) {
            if (transport.responseText.isJSON()) {
                response = transport.responseText.evalJSON()
                if (response.error) {
                    alert(response.message);
                } else {
                    if (layoutdesignForm.getLayoutdesignId() == response['id']) {
                        layoutdesignForm.setLayoutdesignPath(response['path']);
                    }
                }
            }
        };
        new Ajax.Request(
            '<?php echo $this->getRefreshPathUrl() ?>',
            {
                method: 'POST',
                evalScripts: true,
                onSuccess: refreshPathSuccess
            }
        );
    };

    layoutdesignForm.getLayoutdesignId = function () {
        collection = $(this.formId).getInputs('hidden', 'layoutdesign[id]');
        if (collection.size() > 0) {
            return collection.first().value;
        }
        return false;
    };
    layoutdesignForm.setLayoutdesignPath = function (path) {
        collection = $(this.formId).getInputs('hidden', 'layoutdesign[path]');
        if (collection.size() > 0) {
            return collection.first().value = path;
        }
    };
    function layoutdesignSubmit(url, useAjax) {
        var activeTab = $('active_tab_id');
        if (activeTab) {
            if (activeTab.tabsJsObject && activeTab.tabsJsObject.activeTab) {
                activeTab.value = activeTab.tabsJsObject.activeTab.id;
            }
        }
        var params = {};
        var fields = $('layoutdesign_edit_form').getElementsBySelector('input', 'select');
        for(var i=0;i<fields.length;i++) {
            if (!fields[i].name) {
                continue;
            }
            params[fields[i].name] = fields[i].getValue();
        }
        var layoutdesignId = params['layoutdesign[id]'] ? params['layoutdesign[id]'] : 0;
        var isCreating = layoutdesignId == 0;
        var path = params['layoutdesign[path]'].split('/');
        var parentId = path.pop();
        if (parentId == layoutdesignId) {
            parentId = path.pop();
        }
        if (isCreating) {
            if (!tree.currentNodeId) {
                tree.currentNodeId = parentId;
            }
            tree.addNodeTo = parentId;
        } else {
            var currentNode = tree.getNodeById(layoutdesignId);
            var oldClass = 'active-category';
            var newClass = 'active-category';
            if (currentNode) {
                if (parseInt(params['layoutdesign[status]'])) {
                    var oldClass = 'no-active-category';
                    var newClass = 'active-category';
                } else {
                    var oldClass = 'active-category';
                    var newClass = 'no-active-category';
                }
                Element.removeClassName(currentNode.ui.wrap.firstChild, oldClass);
                Element.addClassName(currentNode.ui.wrap.firstChild, newClass);
            }
        }
        layoutdesignForm.submit();
    }
    <?php if ($this->isAjax() && ($block = $this->getLayout()->getBlock('tabs')) && ($_tabsJsObject=$block->getJsObjectName())): ?>
        <?php echo $_tabsJsObject ?>.moveTabContentInDest();
        if (<?php echo $_tabsJsObject ?>.activeTab) {
            $('active_tab_id').value = <?php echo $_tabsJsObject ?>.activeTab.id;
        }
        $('active_tab_id').tabsJsObject = <?php echo $_tabsJsObject ?>;
    <?php endif; ?>
//]]>
</script>
