<?php
$_block_collection = $this->getBlockCollection();
$_design_code = $this->getLayoutDesignCode();
?>
<div id="designer-wrapper">
    <div id="designer-frame">
        <div id="frame-item">
            <div id="layouts-accordion" class="connectedSortable">
                <h3 data='top'>Content top</h3>
                <div class="layout-position" position="top">
                    <ul class="layout-position-container">
                        <?php if (isset($_design_code['top'])): ?>
                            <?php echo $this->items_html($_design_code['top'], 'top') ?>
                        <?php endif; ?>
                    </ul>
                </div>
                <h3>Left sidebar</h3>
                <div class="layout-position" position="left">
                    <ul class="layout-position-container">
                        <?php if (isset($_design_code['left'])): ?>
                            <?php echo $this->items_html($_design_code['left'], 'left') ?>
                        <?php endif; ?>
                    </ul>
                </div>
                <h3>Right sidebar</h3>
                <div class="layout-position" position="right">
                    <ul class="layout-position-container">
                        <?php if (isset($_design_code['right'])): ?>
                            <?php echo $this->items_html($_design_code['right'], 'right') ?>
                        <?php endif; ?>
                    </ul>
                </div>
                <h3>Content Bottom</h3>
                <div class="layout-position" position="bottom">
                    <ul class="layout-position-container">
                        <?php if (isset($_design_code['bottom'])): ?>
                            <?php echo $this->items_html($_design_code['bottom'], 'bottom') ?>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div id="blocks-list">
        <div id="blocks-accordion" class="connectedSortable">
            <h3>Static Blocks</h3>
            <div class="blocks-list-content-wrapper">
                <ul id="static-block" class="connectedSortable">
                    <?php foreach ($_block_collection as $key => $_block): ?>
                        <li class="block-item block-item-listed"
                            title="<?php echo $_block->getTitle() ?>"
                            identifier="<?php echo $_block->getIdentifier() ?>"
                            block_id="<?php echo $_block->getId() ?>">
                                <?php echo $_block->getTitle() ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<style>
    #designer-wrapper {
        width: 100%;
        display: block;
        min-width: 600px;
        box-sizing: border-box;
    }
    #designer-frame {
        width: 60%;
        height: 100%;
        min-height: 500px;
        display: block;
        float: left;
    }
    #blocks-list {
        width: 35%;
        height: 100%;
        min-height: 500px;
        display: block;
        float: right;
    }
    .layout-position {
        display: block;
        margin: 0 0px;
        box-sizing: border-box;
    }
    .layout-position-container {
        margin-bottom: 10px;
        padding: 3px;
        min-height: 50px;
        background: #f1fbea;
    }
    .block-item-listed, .block-item-added {
        padding: 2px 2px 2px 5px;
        border-radius: 2px;
        margin: 0;
        cursor: pointer;
    }
    .block-item-listed {
        background: #EEEEEE;
        border: 1px solid #DDDDDD;
    }
    .block-item-listed:hover, .block-item-added {
        background: #d2fdb2;
        border: 1px solid #d2fdb2;
    }
    a.bt-remove-block{
        float: right;
        text-decoration: none;
        cursor: pointer;
        padding: 0 5px;
        background: #fa9942;
        color: #FFF;
        font-weight: bold;
        border-radius: 2px;
    }
    .ui-accordion-header {
        cursor: pointer;
        border-radius: 2px;
        background: #EEEEEE;
        padding: 0 5px;
        border: 1px solid #DDDDDD;
    }
    .ui-accordion-header:hover {
        background: #FAFAFA;
    }
    .ui-state-highlight { height: 1.5em; line-height: 1.2em; border: 1px dashed yellow; }

</style>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    jQuery(document).ready(function ($) {

        $("ul#static-block").sortable({
            connectWith: "ul.layout-position-container",
            //placeholder: "highlight",
            placeholder: "ui-state-highlight"
        });

        $("ul#content-filter").sortable({
            connectWith: "ul.layout-position-container",
            placeholder: "ui-state-highlight"
        });

        $(".layout-position-container").sortable({
            connectWith: "ul.layout-position-container",
            items: "li",
            placeholder: "highlight",
            receive: function (event, ui) {
                console.log(ui.item);
                //setValue(ui.item);
                setInput(ui.item);
            }
        });

        function setInput(element) {
            var position = $(element).parent().parent().attr('position');
            var identifier = $(element).attr('identifier');

            $(element).find('input').remove();
            $(element).find('a').remove();
            var li = $(element);

            var input = jQuery("<input>");
            input.attr('name', 'layoutdesign[design_frame][' + position + '][]');
            input.attr('value', identifier);
            input.attr('type', 'hidden');
            li.append(input);

            var a_rm = jQuery("<a></a>");
            a_rm.addClass('bt-remove-block');
            a_rm.text('X');
            a_rm.click(function () {
                jQuery(this).parent().remove();
            });
            li.append(a_rm);
        }
        jQuery('.bt-remove-block').click(function () {
            jQuery(this).parent().remove();
        });
    });
</script>
