
<?php $_tags = $this->getTags(); ?>
<?php if ($_tags->getSize() > 0) : ?>
    <div class="tags-list-container">
        <div class="tag-list-item">
            <i class="fa fa-tag" aria-hidden="true"></i>
            <?php
            $count = 1;
            $total = ($_tags->getSize());
            ?>
            <?php foreach ($_tags as $_tag) : ?>
                <?php if ($count == $total || $total == 1) : ?>
                    <a href="#">
                        <?php echo $_tag->getName(); ?>
                    </a>
                <?php else : ?>
                    <a href="<?php echo $_tag > getTaxonomyUrl() ?>">
                        <?php echo $_tag->getName(); ?>
                    </a>
                    <span>,</span>
                    <?php
                    $count++;
                endif;
                ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
