
<?php $_taxonomies = $this->getTaxonomies(); ?>
<?php if ($_taxonomies->getSize() > 0) : ?>
    <div class="taxonomies-list-container">
        <div class="taxonomy-list-item">
            <i class="fa fa-folder-open" aria-hidden="true"></i>
            <?php foreach ($_taxonomies as $_taxonomy) : ?>
                <a href="<?php echo $_taxonomy->getTaxonomyUrl() ?>">
                    <?php echo $_taxonomy->getName(); ?>
                </a>
                <span>,</span>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
