<?php ?>
<?php $_filter = $this->getCurrentFilter(); ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title filter-title">
    <h1><?php echo $_filter->getName(); ?></h1>
</div>
<div class="filter-view">
    <div class="filter-name">
        <?php echo Mage::helper('dls_dlsblog')->__('Name'); ?>:<?php echo $_filter->getName(); ?>

    </div>
    <div class="filter-description">
        <?php echo Mage::helper('dls_dlsblog')->__('Description'); ?>:<?php echo $_filter->getDescription(); ?>

    </div>
    <div class="filter-exposed">
        <?php echo Mage::helper('dls_dlsblog')->__("Exposed filter"); ?>:<?php echo ($_filter->getExposed() == 1) ? Mage::helper('dls_dlsblog')->__('Yes') : Mage::helper('dls_dlsblog')->__('No') ?>

    </div>

</div>
