<?php ?>
<?php $_post = $this->getCurrentPost(); ?>
<?php if ($_post) : ?>
    <div class="post-widget-view">
        <h3><?php echo $_post->getTitile() ?></h3>
        <div>
            <div class="titile-widget">
                <?php echo Mage::helper('dls_dlsblog')->__('Title'); ?>:<?php echo $_post->getTitile(); ?>
            </div>
            <div class="main_content-widget">
                <?php echo Mage::helper('dls_dlsblog')->__('Main content'); ?>:<?php echo $_post->getMainContent(); ?>
            </div>
            <div class="short_content-widget">
                <?php echo Mage::helper('dls_dlsblog')->__('Short content'); ?>:<?php echo $_post->getShortContent(); ?>
            </div>
            <div class="publish_status-widget">
                <?php echo Mage::helper('dls_dlsblog')->__("Publishing status"); ?>:<?php echo $_post->getAttributeText('publish_status'); ?>
            </div>
            <div class="small_image-widget">
                <?php if ($_post->getSmallImage()) : ?>
                    <img src="<?php echo Mage::helper('dls_dlsblog/post_image')->init($_post, 'small_image')->resize(75); ?>" alt="<?php echo $this->escapeHtml($_post->getTitile()); ?>" />
                <?php endif; ?>
            </div>
            <div class="publish_date-widget">
                <?php echo Mage::helper('dls_dlsblog')->__("Publish date"); ?>: <?php echo Mage::helper('core')->formatDate($_post->getPublishDate(), 'full'); ?>
            </div>

        </div>
    </div>
<?php endif; ?>
