<?php

/**
 * Post view widget template
 *
 * @category    DLS
 * @package     DLS_DLSBlog
 * @author      Ultimate Module Creator
 */
?>
<?php $_post = $this->getCurrentPost();?>
<?php if ($_post) :?>
    <div class="post-widget-view">
        <h3><?php echo $_post->getTitle()?></h3>
        <div>
            <div class="title-widget">
                <?php echo Mage::helper('dls_dlsblog')->__('Title');?>:<?php echo $_post->getTitle();?>
            </div>
            <div class="short_content-widget">
                <?php echo Mage::helper('dls_dlsblog')->__('Short content');?>:<?php echo $_post->getShortContent();?>
            </div>
            <div class="small_image-widget">
                <?php if ($_post->getSmallImage()) :?>
    <img src="<?php echo Mage::helper('dls_dlsblog/post_image')->init($_post, 'small_image')->resize(75);?>" alt="<?php echo $this->escapeHtml($_post->getTitle());?>" />
<?php endif;?>
            </div>

        </div>
    </div>
<?php endif;?>
