<?php

/**
 * Taxonomy subtree template
 *
 * @category    DLS
 * @package     DLS_DLSBlog
 * @author      Ultimate Module Creator
 */
?>
<?php $_taxonomies = $this->getTaxonomies(); ?>
<?php if ($_taxonomies->getSize() > 0) :?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/dls_dlsblog/tree.js')?>"></script>
    <ul id="<?php echo $this->getUniqueId()?>">
        <?php foreach ($_taxonomies as $_taxonomy) : ?>
            <?php echo $this->drawTaxonomy($_taxonomy);?>
        <?php endforeach;?>
    </ul>
    <script type="text/javascript">
        dlsblogTree('<?php echo $this->getUniqueId()?>');
    </script>
<?php endif;?>
