<?php 

/**
 * Post Tag list template
 *
 * @category    DLS
 * @package     DLS_DLSBlog
 * @author      Ultimate Module Creator
 */
?>
<?php $_tags = $this->getTags(); ?>
<?php if ($_tags->getSize() > 0) :?>
<div class="page-title tag-title">
    <h2><?php echo Mage::helper('dls_dlsblog')->__('Tags') ?></h2>
</div>
<div class="tags-list-container">
    <?php foreach ($_tags as $_tag) : ?>
        <div class="tag-list-item">
            <?php echo $_tag->getName();?>
<br />
        </div>
    <?php endforeach;?>
</div>
<?php endif;?>
