
<?php $_posts = $this->getPosts(); ?>
<?php if ($_posts->getSize() > 0) : ?>
    <div class="page-title post-title">
        <h2><?php echo Mage::helper('dls_blog')->__('Posts') ?></h2>
    </div>
    <div class="posts-list-container">
        <?php foreach ($_posts as $_post) : ?>
            <div class="post-list-item">
                <a href="<?php echo $_post->getPostUrl() ?>">
                    <?php echo $_post->getTitle(); ?>
                </a><br />
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
